<style>
    h1 {
        text-align: center;
    }

    #myslider img {
        margin: auto !important;
        text-align: center !important;
        width: 600px !important;
        height: 400px !important;
    }

    #myportfolio {
        margin-top: 60px;
        text-align: center;
    }

    #myportfolio img {
        width: 100px !important;
        height: 100px !important;
    }

    #nutan {
        text-align: center;
        margin-top: 10px;
    }
</style>

<?php

$urlMedia = $this->getBaseUrlMedia(); // lấy link tới hình ảnh
$link = $urlMedia . "test/tmp";
$soLuongHienThi = $this->getData("recordrows"); // lấy số lượng portfolio được hiển thị ra, ở trong cái widget ở
// trong etc đã cấu hình
?>
<div id="myslider">
    <h1>My Slider</h1>
    <div class="owl-carousel owl-theme" id="aaaaaaa">
		<?php
        // hàm _beforeToHtml()
		foreach ($this->getData("listPortfolio") as $value) {
			?>
            <div class="item"><img src='<?= $link . "/" . $value['image'] ?>'></div>
			<?php
		}
		?>

    </div>
    <div id="nutan">
        <button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button>
        <button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button>
    </div>
</div>


<!--<div id="myportfolio">
    <h1>My Portfolio</h1>
    <div class="col-md-12">
		<?php
/*		$a = 0;
		foreach ($this->getData("listPortfolio") as $value) {
			$a++;
			if ($a <= $soLuongHienThi) {
				*/?>
                <div class="col-md-6">
                    <img src='<?/*= $link . "/" . $value['thumbnail'] */?>'><br>
                    <b>Client :</b><?/*= $value['client'] */?><br>
                    <b>Project :</b><?/*= $value['project'] */?><br>
                </div>
				<?php
/*			}
		}
		*/?>
    </div>
</div>
-->

<script type="text/javascript">
    require([
        'jquery',
        'owlslider'  // the alias for "mage/accordion"
    ], function ($) {
        $(function () {
            var products_list = $('.owl-carousel');
            products_list.owlCarousel({
                loop: true,
                margin: 10,
                nav: false,
                items: 1,
                autoHeight: true,

            })

            var owl1 = $('#aaaaaaa');
            owl1.owlCarousel();
            // Go to the next item
            $('.owl-prev').click(function () {
                owl1.trigger('next.owl.carousel');
            });
            // Go to the previous item
            $('.owl-next').click(function () {
                owl1.trigger('prev.owl.carousel', [300]);
            });
        });
    });

</script>