<div class="col-md-12" id="portfolio">
    <h1>List Portfolio</h1>
	<?php
	$quantityOnRow = $block->getCategoryNeed()["quantity_portfolio"];
	$linkImage = $block->getBaseURLMedia() . "test/tmp";
	$a = 0;
	if ($quantityOnRow == 2) {
		$c = 6;
	} else if ($quantityOnRow == 3) {
		$c = 4;
	} else if ($quantityOnRow == 4) {
		$c = 3;
	}
	foreach ($block->getCategoryPf() as $value) {
		$a++;
		if ($a <= $quantityOnRow) {
			?>
            <div class="col-md-<?= $c ?> myclass">
                <a href="<?= $block->getUrl("portfolio-detail-" . $value["id"] . "") ?>">
                    <img src="<?= $linkImage . "/" . $value['thumbnail'] ?>"><br><br>
                    <p><?= $value['project'] ?></p>
                </a>
            </div>
			<?php
		} else if ($a > $quantityOnRow) {
			?>
            <div class="cls"></div>
            <br>
            <div class="col-md-<?= $c ?> myclass">
                <a href="<?= $block->getUrl("portfolio-detail-" . $value["id"] . "") ?>">
                    <img src="<?= $linkImage . "/" . $value['thumbnail'] ?>"><br><br>
                    <p><?= $value['project'] ?></p>
                </a>
            </div>
			<?php
			$a = 1;
		}
	}
	?>
</div>

