<meta name="description" content="<?= $block->getCategoryNeed()['meta_description'] ?>">
<meta name="keywords" content="<?= $block->getCategoryNeed()['meta_keywords'] ?>">
<style>
    p {
        text-align: center;
        font-size: 20px;
        color: #0a0a0a;
        font-weight: bold;
    }

    #portfolio {
        text-align: center;
        margin: auto;
    }

    #portfolio .myclass {
        float: left;
        height: 250px;
        text-align: center;
    }

    .myclass img {
        border: 1px solid #0a0a0a;
        padding: 10px;
        width: 200px;
        height: 200px;
        margin-top: 10px;
    }

    .cls {
        clear: left;
        margin-bottom: 5px;
    }
</style>