<style>
    a:hover {
        cursor: pointer;
    }
</style>
<?php
$block->getComment2();
?>
<div class="col-md-12" style="margin-top: 50px;">
    <table id="example2" class="table table-bordered table-hover"
           style="width: 1000px;margin: auto;text-align: center">
        <thead>
        <tr>
            <td>STT</td>
            <td>Portfolio</td>
            <td>Your Comment</td>
            <td>Status</td>
            <td>Delete</td>
        </tr>
        </thead>
        <tbody>
		<?php
		$a = 0;
		foreach ($block->getComment() as $value) {
			$a++;
			?>
            <tr>
                <td><?= $a ?></td>
                <td><?= $value['project'] ?></td>
                <td><?= $value['comment'] ?></td>
				<?php
				if ($value['status_cmt'] == 1) {
					?>
                    <td>Đã duyệt</td>
					<?php
				} else {
					?>
                    <td>Chưa duyệt</td>
					<?php
				}
				?>
                <td><a onclick="xoa(<?= $value['id_cmt'] ?>)">Delete</a></td>
            </tr>
			<?php
		}
		?>
        </tbody>
    </table>
</div>

<script type="text/javascript">
    function xoa(i) {
        require([
            'jquery',
        ], function ($) {
            $.ajax({
                url: "<?= $block->getUrl("blogbig/indexcmt/deletecmt") ?>",
                dataType: "json",
                data: {i: i},
                type: "POST",
                success: function (data) {
                    if (data == 1) {
                        alert("Bạn đã xóa thành công");
                    }
                },
                error: function () {
                }
            });
        });
    }
</script>