<?php
// trong block DetailPf.php
$linkImage = $block->getBaseURLMedia() . "test/tmp";
?>
<style>
    #myimage img:first-child {
        width: 550px !important;
        height: 360px !important;
    }

    #midder {
        margin-top: 20px;
    }

    b {
        font-size: 20px;
    }

    #content {
        margin-top: 30px;
    }

    #mysomething {
        border: 1px solid #e0e0d1;
    }

    #mysomething p {
        padding: 10px;
    }

    #comment {
        margin-bottom: 20px;
        margin-top: 20px;
    }

    #listcomment {
        margin-bottom: 30px;
    }

    a {
        font-size: 12px;
    }

    a:hover {
        cursor: pointer;
    }

</style>

<div class="col-md-12">
    <div class="col-md-12">
        <h1><?= $block->getDetailPf()['project'] ?></h1>
    </div>
</div>
<div class="col-md-12" id="midder">
    <div class="col-md-6" id="myimage">
        <img src="<?= $linkImage . "/" . $block->getDetailPf()['image'] ?>"><br><br><br>
    </div>
    <div class="col-md-6" id="mysomething">
        <p><b>Client : </b><?= $block->getDetailPf()['client'] ?></p>
        <p><b>Skill : </b><?= $block->getDetailPf()['skill'] ?></p>
    </div>
</div>

<div class="col-md-12" id="content">
    <div class="col-md-12">
        <p><b>Content</b></p>
        <p><?= $block->getDetailPf()['content'] ?></p>
    </div>
</div>
<?php
if (!empty($block->getCustomerId())) {
	?>
    <div class="col-md-12" id="comment">
        <div class="col-md-6">
            <label>Comment</label>
            <textarea class="form-control" id="mycomment"></textarea>
            <input type="hidden" value="<?= $block->getDetailPf()['id'] ?>" id="id_portfolio">
            <input type="hidden" class="form-control" id="name" value="<?= $block->getCustomerId()['name'] ?>">
            <input type="hidden" class="form-control" id="id_user" value="<?= $block->getCustomerId()['id'] ?>">
        </div>
        <div class="col-md-3" style="margin-top: 44px;">
            <button type="button" class="btn btn-primary" onclick="thembinhluan()">Bình Luận</button>
        </div>
    </div>

	<?php
} else {
	?>
    <div class="col-md-12" id="comment">
        <div class="col-md-12">
            <b>Bạn cần phải đăng nhập để có thể bình luận</b>
        </div>
    </div>
	<?php
}
?>

<div class="col-md-12" id="listcomment">
	<?php
	foreach ($block->getComment() as $value) {
		?>
        <div class="col-md-12" style="margin-top: 15px;">
            <p><b><?= $value['your_name'] ?></b></p>
            <p><?= $value['comment'] ?></p>
        </div>
		<?php
	}
	?>
</div>

<script type="text/javascript">
    function thembinhluan() {
        require([
            'jquery',
        ], function ($) {
            var comment = $("#mycomment").val();
            var name = $("#name").val();
            var id_portfolio = $("#id_portfolio").val();
            var id_user = $("#id_user").val();
            if (comment != "" && comment != null) {
                $.ajax({
                    url: "<?= $block->getUrl("blogbig/indexcmt/addcmt") ?>",
                    dataType: "json",
                    data: {comment: comment, name: name, id_portfolio: id_portfolio, id_user: id_user},
                    type: "POST",
                    success: function (data) {
                        if (data == 1) {
                            alert("Bạn đã thêm thành công, và cần đợi duyệt");
                            $('#mycomment').val('').trigger('chosen:updated');
                        }
                    },
                    error: function () {
                    }
                });
            } else {
                alert("Bạn chưa điền comment");
            }
        });
    }
</script>

 <span class="your-price"
                      style="color: #000; font-size: 15px;line-height: 20px;text-transform: capitalize; font-weight: 600; float:left;">Your Price</span>